services:
  nestjs-chat-frontend_dev:
    environment:
      - BACKEND_URL
      - WEBSOCKET_URL


    container_name: nestjs-chat-frontend_dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000