services:
  nestjs-chat-frontend_production:
    environment:
      - BACKEND_URL
      - WEBSOCKET_URL


    container_name: nestjs-chat-frontend_production
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: algomax/nestjs-chat-frontend:production
    restart: always
    ports:
      - 3060:3000